language: java
jdk:
  - openjdk8
before_install:
  - sudo apt-get update
  - cd eureka-consumer/
  - echo "Let's start Maven Package!"
  - mvn clean package
  - cd ..
  - echo "We are in the Docker folder!"
script:
  - docker-compose build
before_deploy:
  echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
deploy:
  provider: script
  script:
    docker tag eureka-consumer:latest 0biwanken0bi/eureka-consumer:latest;
    docker push 0biwanken0bi/eureka-consumer;
  on:
    branch: master
notifications:
  email: false