version: '3.4'
services:
  eureka-consumer:
    image: eureka-consumer
    restart: always
    build:
      context: .
      dockerfile: eureka-consumer/Dockerfile
    working_dir: /eureka-consumer
    environment:
      TZ: America/Sao_Paulo    
    ports:
      - "9092:92"
    command: mvn spring-boot:run
    networks:
      - docker-network  
networks:
    docker-network:
        driver: bridge