#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:9091/eureka

server:
  port: 9092
eureka:
  instance:
    hostname: localhost
    port: 8080
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http:http://35.198.23.45:9091/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000
spring:
  application:
    name: ApplicationEurekaClienteConsumer

